### ISSUE TITLE
bip38 support

### ISSUE THREAD

**Issue by y** [ryancdotorg/brainflayer#11]
now that libscrypt is a dependency, how about support for bip38?

https://github.com/bitcoin/bips/blob/master/bip-0038.mediawiki
https://github.com/notespace/bip38-cracker

i've seen several cracking contests, at least one of them is still open:
  https://bitcointalk.org/index.php?topic=1014202

**Comment by ryancdotorg** [comment]
In testing I actually discovered that scrypt-jane is a lot faster, so I'm going to swap out libscrypt for that.

I'm more likely to add support for BIP32 and BIP39. I'm not sure how much sense it would make to add BIP38 support, since the salts actually are random you can't mass-crack them in the same way. If I were going to make a BIP38 cracker I'd probably write it as a patch to john the ripper.

See also https://github.com/cscott/bip38-cracker.

**Comment by y** [comment]
>  I'm not sure how much sense it would make to add BIP38 support, since the salts actually are random you can't mass-crack them in the same way.

no, there are two different varieties of bip38. the salt is random only when EC multiply mode is used.

**Comment by ryancdotorg** [comment]
Oh, you're right, the salt is not random.

Still, not a lot of code in brainflayer is really all that useful here. Brainflayer is designed to simultaneously attack an entire blockchain worth of addresses, so trying to bolt on something to crack at most a few dozen encrypted private keys doesn't make sense to me. It would be better to make a separate program for that.
