### ISSUE TITLE
why 512MBs?

### ISSUE THREAD

**Issue by daedalus** [ryancdotorg/brainflayer#14]
Why BLOOM_SIZE is 512MB, what happens if I double it? would I get less false positives?

**Comment by ryancdotorg** [comment]
As noted in the comments, 512MB is 2^32 bits. Because the bloom filter is used on hash160 values (which have a *mostly* uniform distribution), instead of actually using a hash function, I just did some byte slicing to get bit addresses. If you doubled `BLOOM_SIZE` there would be no impact other than using more memory unless you also changed `BH00`..`BH19` in `bloom.h`. If you do this without significantly decreasing performance on x86_64, I'll accept a patch.

Also, the `-f` option I added late October may be of interest. If you pass that a file produced as `sort -u example.hex | xxd -r -p > example.bin`, all potential matches that pass the bloom filter will be double checked against the full address list.

**Comment by ryancdotorg** [comment]
Closing since there's no further action to be taken.
