### ISSUE TITLE
I can't proceed for installation process

### ISSUE THREAD

**Issue by warrenbitcoin32** [ryancdotorg/brainflayer#146]
I can't proceed for this installation

warhead@warhead-VirtualBox:~$ sudo apt install git clone https://github.com/matchv/brainflayer/find/master
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package clone
E: Unable to locate package https://github.com/matchv/brainflayer/find
E: Couldn't find any package by glob 'https://github.com/matchv/brainflayer/find'
E: Couldn't find any package by regex 'https://github.com/matchv/brainflayer/find'

**Comment by ryancdotorg** [comment]
Hello, you appear to be trying to use @matchv's fork of Brainflayer rather than the official version. Since that has modifications, I am unable to provide support for it. Unfortunately, issues have been disable on the forked repository, but you can contact @matchv via email at matchvoip@gmail.com for assistance.

If you could let me know where you found the instructions telling you to use that repository so I can request they be corrected, I would very much appreciate it.
