### ISSUE TITLE
Searching unhashed private keys

### ISSUE THREAD

**Issue by ghost** [ryancdotorg/brainflayer#158]
Can a brainflayer search for 5, K and L format private keys? I am trying to use it with a crunch program, but it cannot find any known addresses: 

crunch 51 51 SBCDEFGHJKLMNPQRATUVWXYZ123456789abcdefAghijkmnopqrstuvwxyz -t KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3q@@@@@@@@@@@@@@@@@@@ | ./brainflayer -v -t priv -x -b btcaddress.blf -o found.txt

**Comment by Dnock34** [comment]
better to brute force long hash160 list with balance it's work as well as you can see i cracked 1 of them 2 days ago.

[https://www.blockchain.com/btc/address/1G9cimBTwMS9qyDcgQ3zY9oVQm9yFvvuVo](url)

1G9cimBTwMS9qyDcgQ3zY9oVQm9yFvvuVo a62b083323316c1acd949fac03afec0bec955b6f:u:sha256:qw1ftwa

crunch 1 30 qwertyuıopasdfghjklzxcvbnm123456789 | ./brainflayer -v -b hash160.blf -o win.txt

**Comment by ryancdotorg** [comment]
The poster of the previous comment has been blocked for doing crimes (petty as they may be), and I've taken a screenshot of the comment.

@gambler2502 I haven't been working on brainflayer recently due to other things being more interesting.
Generally, it is better to convert the key to hex and then run brainflayer in incremental mode rather than feeding it a series of base58 formatted private keys as the speed is much higher.
