### ISSUE TITLE
Stealing is bad

### ISSUE THREAD

**Issue by drgray** [ryancdotorg/brainflayer#169]
ok i think alot of what you sayd.imagen if i had quantom computer in here and i could brut force any wallet. but
im poor that some night i sleep with empty stomach. is it still a bad thing to take only 1 of satoshi's trasure to survive?
not realy an issue but to clear our consciousness (cd ..)

**Comment by ryancdotorg** [comment]
> if i had quantom computer ... but im poor that some night i sleep with empty stomach

Well, in this scenario, you could simply sell the quantum computer, as it would be unfathomably valuable.

If it wasn't valuable, then the ability to crack any wallet would be useless because everyone would have it.

I'm not sure why anyone thinks I'm going to change my position that cracking other folks' wallets is theft, and that theft is wrong, considering how disgustingly rich (potentially over a hundred million dollars) I would be if I'd gone blackhat with my work in this field.
