### ISSUE TITLE
Is there a way to specify a range of addresses as input so it will quit when it reaches the end address.

### ISSUE THREAD

**Issue by IntrinsicInnovation** [ryancdotorg/brainflayer#192]
Is there a way to specify a range of addresses as input so it will quit when it reaches the end address?  

And, I guess still using the same bloom file is necessary?

Thanks again for the help!

**Comment by tukaanimhaka** [comment]
you can make that change...put a variable for it and check it in the loop. it will make the program slower though..since u need to check...

**Comment by IntrinsicInnovation** [comment]
> you can make that change...put a variable for it and check it in the loop. it will make the program slower though..since u need to check...

I know C#.  what's the best way to learn C?

**Comment by IntrinsicInnovation** [comment]
Wait a minute, supposedly theres a -stride option that does what I need.  does it work?

**Comment by ryancdotorg** [comment]
I pulled in the `-N` option from the develop branch and updated the help screen.

**Comment by tukaanimhaka** [comment]
@ryancdotorg I see you have added 2 options that are the same `-N`. Will this take the right value as needed/

**Comment by IntrinsicInnovation** [comment]
> I pulled in the `-N` option from the develop branch and updated the help screen.

Thanks.  Ryan.  much appreciated.

**Comment by IntrinsicInnovation** [comment]
> @ryancdotorg I see you have added 2 options that are the same `-N`. Will this take the right value as needed/

@tukaanimhaka  , how do you use the -N or -n option?  all I see is "(brainflayer's -n and -k options may help). "

Thanks

**Comment by IntrinsicInnovation** [comment]
And, what about converting this to another language.  Seems scripts are usually python.  Would it be dramatically slower if I converted to that language?  Is it worth doing?

**Comment by tukaanimhaka** [comment]
@IntrinsicInnovation no i dont think you should spend your time converting to python...this c code is very efficient.

**Comment by IntrinsicInnovation** [comment]
> @IntrinsicInnovation no i dont think you should spend your time converting to python...this c code is very efficient.

ok, but I mean if I wanted to, how much slower would it be?

**Comment by ryancdotorg** [comment]
You could get maybe 5% of brainflayer's speed in Python, and even that would be a challenge.

The optimizations in brainflayer have basically no other sensible use case other than cracking keys.

The big ones are that it can use a massive precomputed table to speed up secp256k1 point multiplication, and it does batched affine transforms.

Regarding features, it was never intended to be a "complete" tool. When I was doing research with it, I ran it on dozens of separate computers with scripts managing it. That's why it doesn't have support for threading. Easier just to run independent processes with the skip options.

I'm not going to implement range support for incremental mode. The `-N` flag supports 64 bit values specified in decimal or hex (leading with 0x). If you want to search a range, set the start value and calculate how many keys to the end value. Actual range support would require a general purpose big integer implementation which is not already present.

**Comment by IntrinsicInnovation** [comment]
ok, thanks.  when you say ". The `-N` flag supports 64 bit values specified in decimal or hex (leading with 0x). If you want to search a range, set the start value and calculate how many keys to the end value." 

How would I know when to stop?
