### ISSUE TITLE
sys.excepthook is missing lost sys.stderr

### ISSUE THREAD

**Issue by gaborzal** [ryancdotorg/brainflayer#75]
Hello,
syntax ,,your_generator | brainflayer -v -b example.blf,, are not working for me. 
Error is sys.excepthook is missing lost sys.stderr
Have you an example with < /dev/urandom or so ? :)
Many Thanks

**Comment by ryancdotorg** [comment]
It sounds like you're wrapping brainflayer with python, I can't really help you with that.

Searching for random keys is a terrible idea, do not do it.

There are an astronomical number of valid private keys for every address, so you're better off starting an incremental search from a random start point because that is faster. Even that is a terrible idea that you shouldn't do, as you'll never find anything. Go play the lottery or bet everything on 23 in roulette, the odds are better.
