### ISSUE TITLE
Increment changes

### ISSUE THREAD

**Issue by hamnaz** [ryancdotorg/brainflayer#81]
hello all
anyone have ideo where and what modify for change increment from 1 to 500
./brainflayer -v -I 0000000000000000000000000000000000000000000000000000000000000001 -b example.blf

normal next increment is +1 
i want increment +500
any solution

**Comment by daedalus** [comment]
use: -n 1/500

**Comment by jamesyoungdigital** [comment]
In a similar fashion, but I want to toss out half the keys it generates and not test them at all in -I mode.

If I understand correctly, 

`./brainflayer -v -I 0000.....00001 -b hash160.blf`

this will always increment by 1 exactly, unless -n is given, in hamnaz's question: -n 1/500 to increment by 500 each time, instead of 1.

I'm not sure how I can make use of this, when what I really want is a batch of keys with -I that are exactly N bits in size, with a certain bit being on or off, 1/0.

I came across this:

```
// batch compute the public keys
secp256k1_ec_pubkey_batch_create(Bopt, batch_upub, batch_priv);
```

which seems like a candidate.

And: (default BATCH_MAX = 4096)

```
// BATCH_MAX of pub keys that match the indices of private keys below
unsigned char batch_upub[BATCH_MAX][65] 
// BATCH_MAX of private keys
unsigned char batch_priv[BATCH_MAX][32]
```

So maybe here,

```
// batch compute the public keys
secp256k1_ec_pubkey_batch_create(Bopt, batch_upub, batch_priv);
```

I could add a command line flag to drop the first BATCH_MAX/2 of them, i.e. only the private keys that start with a 1 bit.

For example:
```
0000
0001
0011
0111
1000
1001
1011
1111
```

for keys of 4 bits, there are 8 possibilities, and I want the first half of them gone and not tested.  Is that possible, and where should I be looking?  And can I specify keys of just length N bits?  Like set leading bits to zero in batch_priv[BATCH_MAX][32], e.g.

```
// Only the "top" ones with leading zeros, not sure if these are in sequence
// up the top end of BATCH_MAX
for (int pos = BATCH_MAX/2; pos < BATCH_MAX; pos++) {
     // Force to N bits in size, assume batch_priv[pos][31] are the least significant bits?
     // I want 58 bits of key, which is 7.25 bytes, or 7 bytes plus next 2 bits

     // Not sure what this is:
     // memcpy(priv, batch_priv[Bopt-1], 32);
     // So does that mean a key of 0xcdef would be in batch_priv[pos][0] = cd. batch_priv[pos][1] = ef?

     // If the most significant bits are in batch_priv[pos][0] .. [6] for my 7 bytes, then maybe:
     // Try to zap out everything in batch_priv[pos][8] and up
     memset(&batch_priv[pos][8], 0, 24); 

     // Now to set only the first 2 bits in byte 7, i.e. next after batch_priv[pos][6]
     // Bit setting?
     batch_priv[pos][7] &= 0b11000000;
     // Or is it ???
     batch_priv[pos][7] &= 0b00000011;
}
```

Would it be somewhere after here:

```
// batch compute the public keys
secp256k1_ec_pubkey_batch_create(Bopt, batch_upub, batch_priv);
```

... that I could ditch the first half of all keys that don't start with 1, if they are in that order (like first half all starting with 0, the next half with 1s) then adjust the loop to the top half of BATCH_MAX when I see Iopt somewhere, or in the "loop over the public keys", for (i = 0; i < batch_stopped; ++i) and maybe in here somewhere?

```
if (Iopt) {
          hex(batch_priv[i], 32, batch_line[i], 65);
}
while (pubhashfn[j].fn != NULL) {
          pubhashfn[j].fn(&hash160, batch_upub[i]);
          fprintresult(ofile, &hash160, pubhashfn[j].id, modestr, batch_line[i]);
          ++j;
}
```

Or adjust for for loop to start at BATCH_MAX/2 instead of 0?  Thanks for any help.

**Comment by jamesyoungdigital** [comment]
This is really hard to get my head around.  Admittedly I have a smaller brain than most people who write this type of code... :-/
