### ISSUE TITLE
X Scanner

### ISSUE THREAD

**Issue by hamnaz** [ryancdotorg/brainflayer#89]
Hi all
one more function could make this tool more attractive
already there is sequential search
if scanner is like to pick X and random value (0---f)applied at X,
Example start key
1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
98d44e13f455d916674d38424d39e1cb01xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
98d44e13f45xxxx6674d38424xxxxcb01b2a9132axxxxxxx97a6f8bb7fexx544
xxxxxxxxxx55d916674d38424d39e1cb01b2a9132aacbb7b97a6f8bb7feb2544

where x randomly changed for checking
any suggestion

**Comment by komyaka** [comment]
Случайный поиск и случайное подставление символов ничего не даст, кроме расходов на электричество.


Random search and random substitution of symbols will give nothing but the cost of electricity.

**Comment by hamnaz** [comment]
full node hex search random definitely wrong idea
above you maybe not understand what i asked, its selective searches at different portion of 64 hex

**Comment by komyaka** [comment]
Я понял что Вы хотите.
И говорю еще раз, это бессмысленно

I understand what You want.
And I say again, it's pointless.

**Comment by komyaka** [comment]
Смотрите программу crunch и через неё, через шаблон передавайте данные ...

See the program crunch and through it, through the template transmit data ...

**Comment by komyaka** [comment]
crunch 64 64 0123456789abcdef -t @@00@@00@@00@@00@@00@@00@@00@@00@@00@@00@@00@@00@@00@@00@@00@@00 | brainflayer .........

**Comment by komyaka** [comment]
НО вы не в том направлении думаете... Всё это уже было проработано, в том числе мной))
Нужно думать в направлении  GPU оптимизации...

Сейчас как раз мне пишут программу для этого так как ryanc отказался писать такую программу и в принципе развитие очень медленное. так как он использует более новую версию и ему не выгодны конкуренты))
Моя почта komyaka@gmail.com

BUT you think in the wrong direction ... All this has already been worked out, including by me))
We need to think in the direction of GPU optimization ...

Now I’m writing a program for this because ryanc refused to write such a program and, in principle, development is very slow. since it uses a newer version and competitors are not profitable to it))
My mail is komyaka@gmail.com

**Comment by hamnaz** [comment]
as an otherway use crunch as brainwallet could be, but tested its slpw work
GPU is ggod for next level
but above my ideo as per value x random will chnage some portion of key, its not applied by any other developer
there is already GPU for bitcrack but only sequential, or some other tools for random, no one have apply my idea as random value for specified area of key

**Comment by komyaka** [comment]
Удачи)))))))

**Comment by ryancdotorg** [comment]
Doing any sort of random search is, as @komyaka says, a pointless waste of electricity, and is much slower than sequential search. FWIW, the fastest way to search arbitrary keys is actually by repeated doubling - this is how my private vanitygen tools work.

Bitmasked incremental search is actually something I've been considering implementing - it is useful for recovering damaged keys. An optimized version could operate nearly as fast as a normal incremental search.

Regarding GPU, I simply don't have the time to learn CUDA/OpenCL and implement secp256k1 point multiplications, which are required for non-incremental searches. All of the vanitygen and private key brute force tools I've seen with GPU acceleration only implement point addition or repeated doubling on GPU - the point multiplication is still done on CPU.
